"""add coding problem, test case, submission tables

Revision ID: 4227af303d3e
Revises: 5152c0c95b01
Create Date: 2026-07-11 01:38:17.328505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4227af303d3e'
down_revision: Union[str, Sequence[str], None] = '5152c0c95b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('starter_code', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('companies', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('coding_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['coding_problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coding_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('tests_passed', sa.Integer(), nullable=True),
    sa.Column('tests_total', sa.Integer(), nullable=True),
    sa.Column('complexity_estimate', sa.String(), nullable=True),
    sa.Column('cleanliness_score', sa.Float(), nullable=True),
    sa.Column('naming_score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['coding_problems.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('answers', 'question_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_category', sa.VARCHAR(), nullable=True))
    op.drop_table('coding_submissions')
    op.drop_table('coding_test_cases')
    op.drop_table('coding_problems')
    # ### end Alembic commands ###
