"""add feedback_helpful column to answers

Revision ID: de2d33050e8f
Revises: 765609b6549f
Create Date: 2026-06-26 13:33:52.179193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2d33050e8f'
down_revision: Union[str, Sequence[str], None] = '765609b6549f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('feedback_helpful', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'feedback_helpful')
    # ### end Alembic commands ###
