# backend/update_topic_descriptions.py
#
# One-time (but safely re-runnable) update script: replaces the thin
# placeholder descriptions on existing Topic rows with fuller, technically
# precise explanations that also tie back to what's actually being
# evaluated in an interview context.
#
# Safe by design: this only UPDATEs the `description` column on rows that
# already exist (matched by `name`), never INSERTs or DELETEs. IDs stay
# untouched, so nothing in TopicPrerequisite (which references Topic.id)
# is affected. Run it any time; re-running just overwrites description
# again with the same text.
#
# Usage:
#   cd backend
#   python update_topic_descriptions.py

from database import SessionLocal
from models import Topic

DESCRIPTIONS = {
    # ---------- Foundations ----------
    "variables_and_types": "How a language reserves memory and interprets bits as a specific kind of value: integers, strings, booleans, floats. Static languages (Java, C++) check types at compile time; dynamic languages (Python, JS) check at runtime, trading safety for flexibility. Interviewers watch for whether you reason about type coercion bugs (e.g. '5' + 3 in JavaScript) instead of assuming types are obvious.",
    "control_flow": "The mechanisms — if/else, switch, for, while, early returns — that determine which statements actually execute and in what order. The core skill isn't syntax, it's minimizing nested branching: three levels of nested if/else is usually a sign the logic should be restructured with guard clauses or extracted into functions.",
    "functions": "A named, reusable block that takes parameters, executes a body, and optionally returns a value — the basic unit of decomposition in almost every language. Understanding parameter passing, by value versus by reference, is what separates people who can predict a function's side effects from people who get surprised by them.",
    "recursion": "A function that calls itself on a smaller version of the same problem, always paired with a base case that stops the recursion. Every recursive call adds a frame to the call stack, so unbounded recursion causes a stack overflow — this is the single most common recursion bug interviewers probe for.",
    "complexity_analysis": "Big-O notation describes how an algorithm's runtime or memory grows as input size increases, independent of hardware. The skill interviewers actually score isn't reciting definitions — it's correctly identifying the dominant term in a mixed operation (e.g. recognizing that O(n) preprocessing plus O(log n) per query is still O(n) overall) and explaining trade-offs between time and space.",
    "pointers_and_references": "Direct access to a value's memory address, versus an alias that refers to the same underlying data. Getting this wrong causes two of the most common categories of real bugs: null pointer dereferences, and unintended mutation when multiple references point to the same object.",

    # ---------- Data Structures ----------
    "arrays": "A fixed-size, contiguous block of memory holding elements of the same type — O(1) index access, but O(n) insertion or deletion in the middle since shifting elements is required. Contiguity also makes arrays cache-friendly: sequential memory access is dramatically faster than the scattered access pattern of linked structures.",
    "linked_lists": "A sequence of nodes where each node holds a value and a pointer to the next node, trading an array's O(1) random access for O(1) insertion and deletion at any position, once you already have a reference to it. The classic interview traps are off-by-one errors at the head or tail, and updating pointers in the wrong order during insertion, which silently orphans nodes.",
    "stacks": "A Last-In-First-Out structure supporting push and pop from one end only. Underpins function call stacks, undo operations, and — critically for interviews — the standard technique for converting recursive algorithms like DFS or balanced-parenthesis checking into iterative ones.",
    "queues": "A First-In-First-Out structure where elements are added at the back and removed from the front. The default structure for breadth-first search and any producer-consumer or task-scheduling system, since it naturally processes work in the order it arrived.",
    "hash_maps": "Key-value storage that uses a hash function to compute an array index for each key, giving average O(1) lookup, insert, and delete. The real technical depth is in collision handling (chaining versus open addressing) and load-factor-triggered resizing — most candidates can say 'O(1)' but few can explain what happens when two keys hash to the same bucket.",
    "binary_trees": "A hierarchical structure where each node has at most two children, typically called left and right. Nearly every tree-traversal interview question — preorder, inorder, postorder, level-order — is really testing whether you can reason recursively about a structure that isn't linear.",
    "binary_search_trees": "A binary tree with an ordering invariant — left subtree values are smaller, right subtree values are larger — giving O(log n) search, insert, and delete when the tree is balanced. The catch interviewers exploit: an unbalanced BST, built for example by inserting already-sorted data, degrades to a linked list with O(n) operations.",
    "heaps": "A complete binary tree maintaining a heap-order invariant — parent always smaller than children for a min-heap, larger for a max-heap — giving O(log n) insert and O(1) peek at the min or max element. The go-to structure whenever a problem needs 'the smallest or largest k things so far' without fully sorting everything.",
    "priority_queue": "An abstract queue where each element has a priority and dequeue always returns the highest-priority item, almost always implemented with a heap under the hood. Shows up constantly in problems framed as 'merge k sorted lists' or 'find the k closest points' — recognizing the priority-queue pattern is often the entire insight.",
    "graphs": "A set of nodes (vertices) connected by edges, which can be directed or undirected, weighted or unweighted. The representation you choose — adjacency list versus adjacency matrix — has real performance consequences: adjacency lists win for sparse graphs, matrices win when you need O(1) edge-existence checks.",
    "tries": "A tree where each path from the root spells out a prefix, letting you check whether a string is a prefix of any stored word in O(L) time (L = string length) regardless of how many words are stored. The structure behind autocomplete, spell-check, and IP-routing lookup tables.",
    "segment_trees": "A binary tree built over an array that answers range queries (sum, min, max over a subrange) and applies range updates in O(log n), instead of the O(n) a naive scan would require. A step up in complexity from most interview data structures — worth knowing conceptually even if you rarely implement one from scratch under time pressure.",
    "union_find": "Also called disjoint-set: tracks which elements belong to which group, and can merge two groups or check if two elements are in the same group, both in near-O(1) amortized time using path compression and union by rank. The standard tool for cycle detection in graphs and for Kruskal's minimum-spanning-tree algorithm.",
    "balanced_trees": "Self-balancing binary search trees, like AVL and Red-Black trees, that guarantee O(log n) worst-case operations by automatically restructuring after insertions or deletions that would otherwise create a skewed tree. You're unlikely to implement one from scratch in an interview, but you should be able to explain why a plain BST isn't enough — this comes up in system design discussions about database indexes, which are almost always backed by a balanced tree or B-tree variant.",

    # ---------- Algorithms ----------
    "sorting": "Reordering a collection according to a comparison rule. The interview-relevant part isn't memorizing every algorithm — it's knowing the trade-offs: quicksort is fast in practice but O(n²) worst case, merge sort guarantees O(n log n) but needs O(n) extra space, and stability (preserving the relative order of equal elements) matters more often than people expect.",
    "binary_search": "Repeatedly halving a sorted search space by comparing the target to the midpoint, giving O(log n) time. Deceptively easy to get wrong — off-by-one errors in the boundary conditions ('<=' versus '<') are one of the most common small bugs that trip up otherwise-strong candidates.",
    "two_pointers": "Using two indices that move through a data structure, often from opposite ends or one trailing the other, to avoid nested loops — turning many O(n²) brute-force scans into O(n). Recognizing when a problem, often phrased around pairs, subarrays, or palindromes, fits this pattern is usually the entire difficulty of the question.",
    "sliding_window": "A specialization of two-pointers for contiguous subarray or substring problems: expand a window's right edge, shrink its left edge when a constraint is violated, and track a running result — all in O(n) instead of re-scanning each candidate window. Interviewers use 'longest substring without repeating characters'-style prompts specifically to see if you spot the window pattern instead of brute-forcing.",
    "graph_traversal": "Breadth-first search (queue-based, explores level by level, finds shortest paths in unweighted graphs) and depth-first search (stack or recursion-based, explores as far as possible before backtracking). Almost every graph problem starts by picking the right one of these two — get that choice wrong and the rest of your solution is fighting the wrong tool.",
    "dijkstra": "Finds the shortest path from a source node to all others in a weighted graph with non-negative edge weights, using a priority queue to always expand the currently-closest unvisited node. The critical caveat interviewers test for: it breaks with negative edge weights, at which point you need Bellman-Ford instead.",
    "dynamic_programming": "Solving a problem by breaking it into overlapping subproblems, solving each subproblem once, and storing the result via memoization or tabulation to avoid redundant recomputation. The hardest part isn't the coding — it's correctly identifying the recurrence relation and state, which is why interviewers weight the explanation of your approach as heavily as the working code.",
    "greedy_algorithms": "Making the locally optimal choice at each step without reconsidering past decisions, betting that local optimality leads to global optimality. Works for problems with the 'greedy-choice property,' like activity selection or Huffman coding, but silently produces wrong answers on problems that actually need DP — knowing which category a problem falls into is the real skill.",
    "backtracking": "Exhaustive search that builds a solution incrementally and abandons a partial solution as soon as it can't possibly lead to a valid answer. The standard approach to combinatorial problems like permutations, subsets, N-Queens, and Sudoku — the efficiency win comes entirely from how aggressively you prune invalid branches early.",
    "topological_sort": "A linear ordering of a directed acyclic graph's nodes such that every edge points from an earlier node to a later one — only possible if the graph has no cycles. Comes up whenever a problem is really about dependency ordering: build systems, course prerequisites, task scheduling.",
    "bit_manipulation": "Directly operating on a number's binary representation using AND, OR, XOR, shifts, and masks — used for compact state representation, fast parity or power-of-two checks, and squeezing memory in constrained systems. A niche but recurring interview category since a handful of tricks, like n & (n-1) to clear the lowest set bit, solve a disproportionate number of problems once you know them.",
    "hashing": "The general technique of mapping arbitrary data to a fixed-size value for fast lookup, deduplication, or integrity checking — the mechanism underneath hash maps, but broader, since it also covers cryptographic hashing and consistent hashing for distributed systems. Worth distinguishing from hash maps specifically, since system design questions often ask about hashing, e.g. consistent hashing for sharding, independent of the data-structure use case.",

    # ---------- Operating Systems ----------
    "processes_and_threads": "A process is an independently-running program with its own memory space; a thread is a unit of execution within a process that shares that memory with other threads in the same process. This distinction is the entire reason multithreaded bugs are harder than multiprocess bugs — shared memory means race conditions are possible, isolated memory means they aren't.",
    "concurrency": "Multiple computations making progress during overlapping time periods, not necessarily simultaneously — that's parallelism specifically. The core interview competency is recognizing when shared mutable state creates a race condition, and choosing the right tool — a lock, an atomic operation, immutable data — to prevent it without over-serializing your code.",
    "locks": "Mutexes and semaphores restrict access to a shared resource so only one (mutex) or a limited number (semaphore) of threads can use it at a time. The classic failure mode interviewers ask about is deadlock — two threads each holding a lock the other needs — and the standard prevention strategy is always acquiring locks in a consistent global order.",
    "memory_management": "How a program allocates and reclaims memory: the stack (fast, automatic, fixed-size frames for function calls) versus the heap (flexible size, manual or garbage-collected). Understanding this is what lets you reason about why a deeply recursive function overflows the stack while a large heap-allocated array doesn't, and what garbage collection is actually automating away.",
    "virtual_memory": "An abstraction giving each process its own private address space, translated to physical RAM addresses by the OS using page tables — which is also what makes memory isolation between processes possible. The concept behind why a program can reference more memory than physically exists, via paging to disk, and why one process can't accidentally read another's memory.",
    "scheduling": "The algorithms an OS uses to decide which process or thread runs next on a limited number of CPU cores — round-robin, priority-based, multilevel feedback queues. Less commonly asked directly in coding interviews, but foundational to system design discussions about task queues and load balancing, which use analogous scheduling trade-offs at a different layer.",

    # ---------- Databases ----------
    "sql": "The declarative query language for relational databases — SELECT, JOIN, WHERE, GROUP BY — used to retrieve and manipulate structured data. Interview depth here usually means being able to reason about why a query is slow (missing index, unnecessary full table scan, poorly chosen join order), not just writing syntactically correct SQL.",
    "normalization": "Structuring a relational schema to eliminate redundant data by splitting it across related tables, formalized as normal forms (1NF, 2NF, 3NF). Reduces update anomalies but increases the number of joins needed to reconstruct a full record — the classic trade-off system design interviews probe when they ask whether you'd normalize or denormalize a given schema.",
    "indexing": "A separate, sorted data structure — usually a B-tree or B+-tree, conceptually similar to the balanced trees covered above — that lets the database find rows without scanning the whole table. The trade-off interviewers want you to name unprompted: indexes speed up reads but slow down writes, since every insert or update also has to update the index.",
    "transactions": "A group of database operations that execute as a single atomic unit — either all succeed or all roll back — governed by the ACID properties (Atomicity, Consistency, Isolation, Durability). Isolation levels (read committed, repeatable read, serializable) are where this gets genuinely subtle: stricter isolation prevents more anomalies but costs more performance.",
    "nosql": "A broad category of non-relational databases — document stores like MongoDB, key-value stores like Redis, column-family stores like Cassandra, graph databases — each optimized for a different access pattern rather than a general-purpose relational model. The interview answer isn't 'NoSQL is faster,' it's identifying which specific access pattern in the prompt makes a given NoSQL model a better fit than a relational one.",
    "sharding": "Horizontally partitioning a database across multiple machines by splitting rows, rather than columns, based on a shard key, so no single machine has to hold the entire dataset. The hard part interviewers probe: choosing a shard key that avoids hot spots, and how you handle queries that need to join across shards.",
    "replication": "Maintaining copies of the same data on multiple nodes for availability and read scalability. Leader-follower replication (single writer, multiple readers) is simpler but has a single point of write failure; multi-leader and leaderless replication solve that at the cost of needing conflict resolution when writes happen concurrently on different nodes.",

    # ---------- Networking ----------
    "networking": "The layered stack: TCP/IP for reliable, ordered delivery; UDP for fast, unordered delivery; HTTP built on top of TCP for request/response semantics. Interview-relevant distinction: TCP's reliability comes from handshakes and retransmission, which is exactly the overhead you're trading away when a system design answer proposes UDP for something latency-sensitive like video streaming.",
    "load_balancing": "Distributing incoming traffic across multiple servers using a strategy — round robin, least connections, consistent hashing — so no single server is overwhelmed. Consistent hashing specifically matters because it minimizes redistribution when servers are added or removed, unlike naive modulo-based hashing, which reshuffles almost everything.",
    "dns": "The system that resolves human-readable domain names to IP addresses, structured as a hierarchical, heavily-cached lookup: root servers, then TLD servers, then authoritative servers. Comes up in system design when discussing how clients initially find a service, and in discussions of DNS-based load balancing and failover.",
    "rest_apis": "An architectural style for web APIs built around stateless requests, standard HTTP verbs mapped to CRUD operations, and resource-based URLs. The interview signal isn't reciting the REST constraints — it's whether you can design a resource model, meaning URLs, status codes, request and response shapes, that's actually consistent and predictable.",
    "websockets": "A persistent, full-duplex connection between client and server, unlike HTTP's request-response model, letting the server push data without the client asking first. The right choice specifically when a system needs true real-time bidirectional updates — chat, live collaboration, live telemetry — and the wrong choice when simple polling or long-polling would do.",
    "grpc": "A high-performance RPC framework using Protocol Buffers for binary serialization and HTTP/2 for transport, giving lower overhead than JSON-over-HTTP and native support for streaming. The system design trade-off: faster and more efficient for internal service-to-service calls, but less human-debuggable and less broadly compatible than REST for public-facing APIs.",

    # ---------- System Design ----------
    "caching": "Storing a copy of expensive-to-compute or expensive-to-fetch data somewhere faster to access, with an eviction policy — LRU, LFU, TTL — deciding what gets removed when the cache fills up. The interview depth is in cache invalidation, famously called the 'hard problem' in computer science, and choosing a read-through, write-through, or write-behind strategy for a given consistency requirement.",
    "microservices": "Structuring a system as a collection of independently deployable services, each owning its own data, communicating over the network rather than in-process function calls. Trades the simplicity of a monolith for independent scalability and deployment, at the cost of network latency, distributed debugging, and the need for service discovery and inter-service contracts.",
    "message_queues": "Asynchronous communication where a producer publishes a message and a consumer processes it later, decoupling the two in time and letting the system absorb traffic spikes. The key design decisions interviewers probe: at-least-once versus exactly-once delivery guarantees, and how you handle a poison message that repeatedly fails processing.",
    "scalability": "The ability of a system to handle increased load, achieved either vertically (a bigger machine) or horizontally (more machines). Vertical scaling is simpler but hits a hard ceiling and a single point of failure; horizontal scaling requires the system to be designed for statelessness and partitioning from the start, which is why it's harder to retrofit.",
    "consistency_models": "The guarantees a distributed system makes about when a write becomes visible to subsequent reads — strong consistency, where every read sees the latest write at the cost of latency and availability, versus eventual consistency, where reads may be temporarily stale but availability and latency improve. This is the practical, concrete version of the abstract CAP theorem trade-off.",
    "consensus": "Protocols like Raft and Paxos that let a distributed set of nodes agree on a single value or ordering of events even when some nodes fail or messages are delayed. The mechanism underneath distributed leader election and the strongly-consistent replicated logs that systems like etcd and ZooKeeper are built on — advanced, but a strong signal of depth when a candidate can explain it correctly.",
    "distributed_systems": "Systems where components run on multiple networked machines and coordinate to behave as one, which introduces failure modes that don't exist on a single machine: partial failure, network partitions, and clock skew between nodes. Most senior-level system design interviews are really testing how you reason about these failure modes, not just whether you can draw boxes and arrows.",
    "cdn": "A geographically distributed network of caching servers, or edge nodes, that serve static — and increasingly dynamic — content from a location physically close to the requesting user, cutting latency and offloading the origin server. The design question interviewers ask: what happens on a cache miss at the edge, and how do you invalidate content across every edge node when it changes.",
    "rate_limiting": "Restricting how many requests a client can make in a given time window, using algorithms like token bucket (allows bursts up to a capacity) or sliding window (smooths enforcement over time). Used both defensively, to prevent abuse or DDoS, and for fair resource allocation between tenants in a multi-tenant system.",
    "api_gateway": "A single entry point that sits in front of a set of backend services, handling routing, authentication, rate limiting, and request or response transformation in one place instead of duplicating that logic in every service. Simplifies the client's view of a microservices architecture at the cost of becoming a potential single point of failure if not itself made highly available.",
    "event_driven_architecture": "Services communicate by publishing and reacting to events rather than making direct synchronous calls to each other, which decouples producers from consumers and lets new consumers be added without changing the producer. The trade-off worth naming unprompted: much better for scalability and loose coupling, much harder to trace a request's full path when debugging, since there's no single call stack to follow.",
    "disaster_recovery": "The strategy and infrastructure for restoring service after a major failure — a region outage, data corruption, a catastrophic bug — usually measured by two numbers: RTO, how long until service is restored, and RPO, how much data loss is acceptable. Interview-relevant because it forces you to commit to concrete trade-offs: multi-region active-active is expensive but has near-zero RTO/RPO, while backups-only is cheap but can mean hours of downtime and data loss.",

    # ---------- Machine Learning ----------
    "linear_algebra": "Vectors, matrices, and the operations on them — dot products, matrix multiplication, eigenvalues — that underlie almost every ML model's internal representation and computation. Neural network layers are, mechanically, just matrix multiplications, which is why linear algebra fluency is treated as a prerequisite rather than optional background.",
    "statistics": "Probability distributions, hypothesis testing, and inference — the mathematical foundation for reasoning about uncertainty, which is what a model's predictions fundamentally are. Comes up directly in interview questions about A/B testing significance, and in explaining why a model's confidence score means something specific rather than a vague 'how sure' number.",
    "calculus": "Derivatives and gradients, the rate of change of a function, are the mathematical machinery that makes it possible to know which direction to adjust a model's parameters to reduce error. Without this, gradient descent is just a black-box procedure instead of something you can actually reason about.",
    "machine_learning_basics": "The core distinction between supervised learning, using labeled training data to predict a known target, and unsupervised learning, finding structure in unlabeled data, plus the basic training/validation/test split workflow. The foundational vocabulary everything else in this category assumes you already have.",
    "overfitting": "When a model learns the noise and idiosyncrasies of its training data rather than the underlying pattern, performing well on training data but poorly on new data — diagnosed by a growing gap between training and validation performance. Regularization, via L1/L2 penalties or dropout, is the standard toolkit for controlling it, and explaining why a specific technique helps, rather than just naming it, is what separates a strong answer.",
    "gradient_descent": "The optimization algorithm that adjusts a model's parameters step by step in the direction that most reduces error, using the gradient computed via calculus. Variants — stochastic, mini-batch, Adam — trade off convergence speed, stability, and computational cost per step, and knowing which one a given training setup uses and why is a common follow-up question.",
    "neural_networks": "Layers of interconnected nodes where each connection has a learned weight, and non-linear activation functions between layers let the network represent non-linear relationships instead of collapsing into a single linear transformation. Backpropagation is the algorithm that computes how much each weight contributed to the final error, using the chain rule from calculus.",
    "cnn": "Convolutional neural networks apply a small, shared filter across an image or grid-structured data to detect local patterns like edges and textures, with those patterns composing into more complex features in deeper layers. The parameter-sharing in convolution is what makes CNNs dramatically more efficient than a fully-connected network for image data — worth explaining specifically, not just 'CNNs are for images.'",
    "rnn": "Recurrent neural networks process sequences by maintaining a hidden state that carries information from previous time steps forward, making them naturally suited to data where order matters, like text and time series. The well-known limitation interviewers probe is vanishing gradients over long sequences — the specific problem that both LSTMs and, later, transformers were designed to solve.",
    "attention_mechanism": "Lets a model learn to weight different parts of the input differently when producing each part of the output, instead of compressing the entire input into one fixed-size hidden state the way an RNN does. This solves the RNN's long-sequence information bottleneck directly, and is the mechanism the entire transformer architecture is built around.",
    "transformer_architecture": "An architecture built entirely on self-attention, with no recurrence at all, which lets every position in a sequence attend to every other position directly and — critically — allows the whole sequence to be processed in parallel rather than step by step. That parallelism is the specific reason transformers scale to model sizes that RNNs never could.",
    "embeddings": "Dense, fixed-size vector representations of discrete objects — words, users, items — learned such that semantically similar objects end up close together in the vector space. The technique that makes similarity search over a database of items computationally tractable, and the underlying idea behind the retrieval pattern used to pull relevant context into an LLM prompt.",
    "model_evaluation": "Metrics beyond raw accuracy — precision, recall, F1 score, ROC-AUC — needed specifically because accuracy is misleading on imbalanced datasets, where a model that always predicts 'not fraud' can be 99% accurate and completely useless. Knowing which metric to optimize for a given business problem, and explaining the precision/recall trade-off concretely, is the actual interview signal here.",

    # ---------- Software Design ----------
    "oop": "The four pillars: encapsulation (hiding internal state), inheritance (sharing behavior across a type hierarchy), polymorphism (treating different types uniformly through a shared interface), and abstraction (exposing only what's necessary). Interviewers care less about textbook definitions and more about whether you can point to a real design decision where one of these pillars was the right, or wrong, choice.",
    "solid_principles": "Five guidelines for maintainable object-oriented design: Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion. Less about reciting the acronym and more about recognizing when a piece of code violates one — a class doing three unrelated things is a Single Responsibility violation whether or not you name it that way.",
    "design_patterns": "Reusable solutions to recurring design problems — Singleton, Factory, Observer, Strategy, and others — that give engineers a shared vocabulary for describing a structure without re-explaining it from scratch. The interview trap: using a pattern because you know its name, not because the problem actually needs it. Overengineering with patterns is a real signal interviewers watch for.",
    "dependency_injection": "Instead of a class constructing the objects it depends on internally, those dependencies are provided, or injected, from outside — usually through the constructor. Makes code dramatically easier to unit test, since you can inject a mock dependency instead of the real one, and is the concrete mechanism behind the abstract Dependency Inversion principle from SOLID.",

    # ---------- Security ----------
    "authentication": "Verifying that a user or system is who they claim to be — passwords, biometrics, multi-factor authentication, or a token issued after an earlier successful login. Distinct from authorization in a way interviewers specifically test: authentication answers 'who are you,' authorization answers 'what are you allowed to do.'",
    "authorization": "Determining what an already-authenticated user or system is permitted to do — role-based access control, permission scopes, resource-level ownership checks. The common real-world bug this category tests for: checking authentication but forgetting authorization, letting a logged-in user access another user's data simply because they're logged in at all.",
    "encryption": "Transforming data so it's unreadable without a key — symmetric encryption, one shared key, fast, used for bulk data, versus asymmetric encryption, a public/private key pair, slower, used for key exchange and signatures. Understanding why real systems use both together — asymmetric to securely exchange a symmetric key, then symmetric for the actual data — is more valuable than memorizing either algorithm's internals.",
    "jwt_tokens": "A signed, self-contained token format for stateless authentication — the server can verify a JWT's signature without a database lookup, since the token itself carries the claims. The trade-off worth naming unprompted: statelessness makes JWTs fast and scalable, but also makes them hard to revoke early, since there's no server-side session to simply delete.",
    "oauth": "A delegated authorization protocol that lets a user grant a third-party application limited access to their data on another service, without ever sharing their password with that third party. The mechanism behind every 'Sign in with Google' button — worth being able to explain the actual token exchange flow, not just that it 'lets you log in with Google.'",
    "sql_injection": "A vulnerability where untrusted user input is concatenated directly into a SQL query, letting an attacker inject their own SQL logic — the classic example being a login form where entering ' OR '1'='1 bypasses password checking entirely. Prevented with parameterized queries and prepared statements, which treat user input strictly as data and never as executable query syntax.",

    # ---------- Behavioral ----------
    "behavioral_storytelling": "The STAR framework — Situation, Task, Action, Result — structures an answer to 'tell me about a time when...' so it has a clear arc instead of rambling. The most common failure mode isn't lacking a good story, it's spending so long on Situation and Task that there's no room left to actually describe your specific Actions and the measurable Result.",
    "leadership": "Influencing outcomes and people without necessarily having formal authority over them — setting direction, unblocking teammates, making a call under ambiguity. Interviewers specifically listen for whether you can describe your individual actions and reasoning, not just narrate what 'the team' did.",
    "conflict_resolution": "Handling genuine technical or interpersonal disagreement professionally — disagreeing with a decision while still being able to explain the other person's reasoning fairly. The strongest answers show you sought to understand the other position before arguing your own, and describe how the disagreement was actually resolved, not just that it existed.",
    "ownership": "Taking initiative and accountability for outcomes beyond the narrow scope you were explicitly assigned — noticing a problem nobody asked you to fix and following through on it anyway. What separates a strong ownership story from a generic one is specificity: what exactly did you notice, what did you personally decide to do about it, and what was the concrete outcome.",
    "communication": "Explaining a technical concept clearly to an audience that doesn't share your context — a non-technical stakeholder, a teammate from a different part of the codebase, an interviewer hearing the problem for the first time. The skill being tested is calibration: can you adjust the level of detail and jargon to the listener, not just whether you understand the concept yourself.",
    "growth_mindset": "Treating failure and critical feedback as information to act on rather than a verdict on your ability — the willingness to say 'I was wrong about X, here's what I changed.' Strong interview answers here are specific about what actually changed in how you work afterward, not just an acknowledgment that a mistake happened.",
    "decision_making": "Choosing a course of action under incomplete information and genuine trade-offs, where there often isn't a clean correct answer. What interviewers weight most heavily is the reasoning process — what factors you considered, what you deliberately chose to deprioritize, and why — over whether the outcome turned out well in hindsight.",
}


def update_descriptions():
    db = SessionLocal()
    updated = 0
    missing = []
    try:
        for name, desc in DESCRIPTIONS.items():
            topic = db.query(Topic).filter(Topic.name == name).first()
            if not topic:
                missing.append(name)
                continue
            topic.description = desc
            updated += 1
        db.commit()
        print(f"Updated {updated} topic descriptions.")
        if missing:
            print(f"Warning: {len(missing)} names in DESCRIPTIONS not found in DB: {missing}")
        unseeded = set(DESCRIPTIONS.keys())
        total_topics = db.query(Topic).count()
        if total_topics != len(DESCRIPTIONS):
            print(f"Note: DB has {total_topics} topics total, DESCRIPTIONS covers {len(DESCRIPTIONS)}. "
                  f"If these don't match, some topics still have old placeholder text.")
    finally:
        db.close()


if __name__ == "__main__":
    update_descriptions()