"""add elo_after to coding submissions

Revision ID: 79235a304a9c
Revises: b3d7f1e9a204
Create Date: 2026-08-24 00:59:27.304006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79235a304a9c'
down_revision: Union[str, Sequence[str], None] = 'b3d7f1e9a204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coding_submissions', sa.Column('elo_after', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coding_submissions', 'elo_after')
    # ### end Alembic commands ###
