"""add question_embeddings table

Revision ID: b8668a5e2168
Revises: 56b8b5cf794a
Create Date: 2026-07-23 00:32:29.911800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8668a5e2168'
down_revision: Union[str, Sequence[str], None] = '56b8b5cf794a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('companies', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_embeddings')
    # ### end Alembic commands ###
