"""Add persona column to InterviewSession

Revision ID: e537e66850df
Revises: b8668a5e2168
Create Date: 2026-08-01 20:30:54.301142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e537e66850df'
down_revision: Union[str, Sequence[str], None] = 'b8668a5e2168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('persona', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'persona')
    # ### end Alembic commands ###
