"""add missing fk indexes and cascade deletes

Revision ID: f02ffa4a5c3a
Revises: e537e66850df
Create Date: 2026-08-09 14:34:01.821644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02ffa4a5c3a'
down_revision: Union[str, Sequence[str], None] = 'e537e66850df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_answers_session_id'), 'answers', ['session_id'], unique=False)
    op.drop_constraint(op.f('answers_session_id_fkey'), 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_coding_submissions_problem_id'), 'coding_submissions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_coding_submissions_user_id'), 'coding_submissions', ['user_id'], unique=False)
    op.drop_constraint(op.f('coding_submissions_user_id_fkey'), 'coding_submissions', type_='foreignkey')
    op.drop_constraint(op.f('coding_submissions_problem_id_fkey'), 'coding_submissions', type_='foreignkey')
    op.drop_constraint(op.f('coding_submissions_session_id_fkey'), 'coding_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'coding_submissions', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'coding_submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'coding_submissions', 'coding_problems', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_coding_test_cases_problem_id'), 'coding_test_cases', ['problem_id'], unique=False)
    op.drop_constraint(op.f('coding_test_cases_problem_id_fkey'), 'coding_test_cases', type_='foreignkey')
    op.create_foreign_key(None, 'coding_test_cases', 'coding_problems', ['problem_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('company_topic_weights_topic_id_fkey'), 'company_topic_weights', type_='foreignkey')
    op.create_foreign_key(None, 'company_topic_weights', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('replay_manifests_session_id_fkey'), 'replay_manifests', type_='foreignkey')
    op.create_foreign_key(None, 'replay_manifests', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('scoring_jobs_session_id_fkey'), 'scoring_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'scoring_jobs', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('topic_prerequisites_topic_id_fkey'), 'topic_prerequisites', type_='foreignkey')
    op.drop_constraint(op.f('topic_prerequisites_prerequisite_id_fkey'), 'topic_prerequisites', type_='foreignkey')
    op.create_foreign_key(None, 'topic_prerequisites', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'topic_prerequisites', 'topics', ['prerequisite_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_prerequisites', type_='foreignkey')
    op.drop_constraint(None, 'topic_prerequisites', type_='foreignkey')
    op.create_foreign_key(op.f('topic_prerequisites_prerequisite_id_fkey'), 'topic_prerequisites', 'topics', ['prerequisite_id'], ['id'])
    op.create_foreign_key(op.f('topic_prerequisites_topic_id_fkey'), 'topic_prerequisites', 'topics', ['topic_id'], ['id'])
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_constraint(None, 'scoring_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('scoring_jobs_session_id_fkey'), 'scoring_jobs', 'sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'replay_manifests', type_='foreignkey')
    op.create_foreign_key(op.f('replay_manifests_session_id_fkey'), 'replay_manifests', 'sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'company_topic_weights', type_='foreignkey')
    op.create_foreign_key(op.f('company_topic_weights_topic_id_fkey'), 'company_topic_weights', 'topics', ['topic_id'], ['id'])
    op.drop_constraint(None, 'coding_test_cases', type_='foreignkey')
    op.create_foreign_key(op.f('coding_test_cases_problem_id_fkey'), 'coding_test_cases', 'coding_problems', ['problem_id'], ['id'])
    op.drop_index(op.f('ix_coding_test_cases_problem_id'), table_name='coding_test_cases')
    op.drop_constraint(None, 'coding_submissions', type_='foreignkey')
    op.drop_constraint(None, 'coding_submissions', type_='foreignkey')
    op.drop_constraint(None, 'coding_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('coding_submissions_session_id_fkey'), 'coding_submissions', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key(op.f('coding_submissions_problem_id_fkey'), 'coding_submissions', 'coding_problems', ['problem_id'], ['id'])
    op.create_foreign_key(op.f('coding_submissions_user_id_fkey'), 'coding_submissions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_coding_submissions_user_id'), table_name='coding_submissions')
    op.drop_index(op.f('ix_coding_submissions_problem_id'), table_name='coding_submissions')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key(op.f('answers_session_id_fkey'), 'answers', 'sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_answers_session_id'), table_name='answers')
    # ### end Alembic commands ###
