# backend/api/routes/meta.py
# Public, read-only catalogue routes: health, companies, roles, topics, study plans.

import structlog
from fastapi import APIRouter, Depends, Request
from fastapi.responses import JSONResponse
from sqlalchemy import text

from api import services
from api.deps import get_current_user_id, limiter
from api.errors import APIError
from database import SessionLocal
from engines.adaptive_difficulty import ROLE_ELO_BANDS
from engines.company_dna import is_known_company
from models import Answer, InterviewSession, Topic, TopicPrerequisite

logger = structlog.get_logger()
router = APIRouter(tags=["catalogue"])


@router.get("/companies/{company}/profile")
@limiter.limit("30/minute")
def get_company_profile(company: str, request: Request, user_id: int | None = Depends(get_current_user_id)):
    """The built-in profiles are public. Any other name is generated by a
    paid Claude call, so it needs an account and is rate limited —
    previously anyone could loop over made-up names and run up the bill."""
    if len(company) > 50:
        raise APIError(422, "company: String should have at most 50 characters")
    if not is_known_company(company) and not user_id:
        raise APIError(401, "Sign in to generate a profile for a new company")
    return services.company_engine.get_profile(company)


@router.get("/roles/elo-bands")
def get_elo_bands():
    return ROLE_ELO_BANDS


@router.get("/health")
def health_check():
    """
    Real readiness check: pings Postgres (required) and Redis (optional,
    every Redis use in this app fails open). Returns 503 if the database is
    unreachable, so Railway's healthcheck and the dashboard status dot
    report an outage instead of a cheerful "ok" from a process that can't
    serve a single real request.
    """
    db_ok = True
    db = SessionLocal()
    try:
        db.execute(text("SELECT 1"))
    except Exception as e:
        db_ok = False
        logger.error("health_check_db_failed", error=str(e))
    finally:
        db.close()

    redis_ok = False
    if services.redis_client:
        try:
            redis_ok = bool(services.redis_client.ping())
        except Exception:
            redis_ok = False

    body = {
        "status": "ok" if db_ok else "degraded",
        "database": "ok" if db_ok else "unreachable",
        "cache": "ok" if redis_ok else "unavailable",
    }
    return JSONResponse(status_code=200 if db_ok else 503, content=body)


@router.get("/")
def root():
    return {"message": "Welcome to InterviewCoach AI"}


@router.get("/companies")
def list_companies():
    return {"companies": services.company_engine.list_companies()}


@router.get("/topics")
def list_topics():
    db = SessionLocal()
    try:
        topics = db.query(Topic).order_by(Topic.category, Topic.name).all()
        return {
            "topics": [
                {"name": t.name, "category": t.category, "difficulty": t.difficulty_level}
                for t in topics
            ]
        }
    finally:
        db.close()


@router.get("/topics/status")
def get_topics_status(user_id: int = Depends(get_current_user_id)):
    """
    Real per-topic status, assembled from data that already exists but was
    never combined into one payload:
      - "gap":         topic name appears in this user's Answer.gaps_identified
      - "passed":      topic appears in Answer.topics_covered but was never
                        flagged as a gap
      - "locked":      topic has a prerequisite (TopicPrerequisite) that this
                        user has not touched yet
      - "unattempted": everything else — honest default, not fabricated

    If the caller isn't logged in, every topic is "unattempted" since there's
    no user history to derive status from.
    """
    db = SessionLocal()
    try:
        all_topics = db.query(Topic).order_by(Topic.category, Topic.name).all()
        base = [{"name": t.name, "category": t.category, "difficulty": t.difficulty_level} for t in all_topics]

        if not user_id:
            return {"topics": [{**t, "status": "unattempted"} for t in base]}

        answers = db.query(Answer).join(
            InterviewSession, Answer.session_id == InterviewSession.id
        ).filter(InterviewSession.user_id == user_id).all()

        touched = set()
        gapped = set()
        gap_urgency = {}  # topic name -> highest urgency seen ("critical" > "high" > "medium" > "low")
        urgency_rank = {"critical": 3, "high": 2, "medium": 1, "low": 0}
        for a in answers:
            for t in (a.topics_covered or []):
                if isinstance(t, str):
                    touched.add(t)
            for g in (a.gaps_identified or []):
                if not isinstance(g, dict):
                    continue  # malformed entry — skip rather than crash the whole route
                name = g.get("gap")
                if not name:
                    continue
                gapped.add(name)
                u = g.get("urgency", "low")
                if urgency_rank.get(u, 0) > urgency_rank.get(gap_urgency.get(name, "low"), 0):
                    gap_urgency[name] = u

        topic_by_id = {t.id: t.name for t in all_topics}
        prereqs = db.query(TopicPrerequisite).all()
        locked = set()
        prereq_map = {}  # topic name -> list of real prerequisite names
        for p in prereqs:
            topic_name = topic_by_id.get(p.topic_id)
            prereq_name = topic_by_id.get(p.prerequisite_id)
            if not topic_name or not prereq_name:
                continue
            prereq_map.setdefault(topic_name, []).append(prereq_name)
            if prereq_name not in touched:
                locked.add(topic_name)

        result = []
        for t in base:
            name = t["name"]
            if name in gapped:
                status = "gap"
            elif name in locked:
                status = "locked"
            elif name in touched:
                status = "passed"
            else:
                status = "unattempted"
            entry = {**t, "status": status, "prerequisites": prereq_map.get(name, [])}
            if status == "gap":
                entry["urgency"] = gap_urgency.get(name, "low")
            result.append(entry)

        return {"topics": result}
    finally:
        db.close()


@router.get("/study-plan/{topic_name}")
def get_study_plan(topic_name: str, company: str = None):
    """
    Returns the full prerequisite chain for a topic, with company
    relevance weighting if a company is specified.
    """
    path = services.gap_engine.get_full_study_path(topic_name)
    db = SessionLocal()
    try:
        # Batched: one query for every topic in the path instead of one
        # query PER step (same fix as /user/sessions, /coding/submissions).
        topics_by_name = {}
        if path:
            all_topics = db.query(Topic).filter(Topic.name.in_(path)).all()
            topics_by_name = {t.name: t for t in all_topics}

        steps = []
        for step_name in path:
            topic = topics_by_name.get(step_name)
            if not topic:
                continue
            weight = services.gap_engine._get_company_weight(db, topic.id, company)
            steps.append({
                "name": step_name,
                "category": topic.category,
                "difficulty": topic.difficulty_level,
                "description": topic.description,
                "company_relevance": weight
            })
        return {"topic": topic_name, "company": company, "steps": steps}
    finally:
        db.close()
